"""Session-plan **field guide** — render tonight's plan to a printable Markdown
document, and manage the saved guides under the store's ``Plans/`` axis (Qt-free).

A field guide is a human-readable observing plan: the night's dark window + moon,
then the ordered target list (best time = transit, altitude, the up-window, moon
separation, filter, and any notes). It's plain Markdown so the app renders it with
``QTextBrowser.setMarkdown`` (Qt-native — no dependency) and it prints/shares.

Device-automation formats (SSC / NINA) are deferred; this is the universal,
telescope-agnostic slice.
"""
from __future__ import annotations

import re
from datetime import date, datetime
from pathlib import Path

from . import catalog, config, prioritize


def _hm(t) -> str:
    return t.strftime("%H:%M") if isinstance(t, datetime) else "—"


def _slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").strip().lower()).strip("-")
    return s or "plan"


def render_markdown(site, day: date, plan: dict, *, title: str | None = None) -> str:
    """Render ``plan`` (from ``planning.plan_night``) to a Markdown field guide."""
    try:
        lib = catalog.load_library()
    except Exception:
        lib = {}
    ref = catalog.load_reference()
    dusk, dawn = plan.get("window", (None, None))
    moon = plan.get("moon", {}) or {}
    entries = plan.get("entries", [])

    heading = title or f"Observing plan — {day.isoformat()}"
    lines = [f"# {heading}", ""]
    lines.append(f"**Site:** {site.name}  ")
    if dusk and dawn:
        lines.append(f"**Astro dark:** {_hm(dusk)} – {_hm(dawn)}  ")
    illum = moon.get("illum")
    if illum is not None:
        lit = f"{round(illum * 100)}% lit"
        alt = moon.get("alt")
        where = f", {'up' if (alt or -1) > 0 else 'down'} at dusk ({alt:.0f}°)" if alt is not None else ""
        lines.append(f"**Moon:** {lit}{where}  ")
    lines.append("")

    if not entries:
        lines.append("_No targets are up tonight from this site._")
        return "\n".join(lines) + "\n"

    lines.append(f"## Targets ({len(entries)}) — in shooting order")
    lines.append("")
    lines.append("| # | Object | Best time | Alt | Up-window | Moon° | Filter |")
    lines.append("|---|--------|-----------|-----|-----------|-------|--------|")
    for i, e in enumerate(entries, 1):
        slug = e["slug"]
        entry = lib.get(slug) or ref.get(slug) or {}
        name = catalog.object_label(catalog.object_identifiers(slug, entry)) or slug
        filt = prioritize.filter_for_type(entry.get("type", ""))
        win = f"{_hm(e['up_start'])}–{_hm(e['up_end'])}"
        lines.append(f"| {i} | {name} | {_hm(e['transit_time'])} | "
                     f"{e['transit_alt']:.0f}° | {win} | {e['moon_sep_deg']:.0f} | {filt} |")
    lines.append("")

    # Per-target notes (season + the library `notes`/remarks), when present.
    detail = []
    for e in entries:
        slug = e["slug"]
        entry = lib.get(slug) or ref.get(slug) or {}
        note = (entry.get("notes") or "").strip()
        season = entry.get("season") or ""
        if note or season:
            name = catalog.object_label(catalog.object_identifiers(slug, entry)) or slug
            bits = " · ".join(x for x in (f"season {season}" if season else "", note) if x)
            detail.append(f"- **{name}** — {bits}")
    if detail:
        lines.append("## Notes")
        lines.append("")
        lines.extend(detail)
        lines.append("")

    lines.append(f"<sub>Generated by M110 · {day.isoformat()}</sub>")
    return "\n".join(lines) + "\n"


# ── saved guides under Plans/ ─────────────────────────────────────────────────

def _plans_dir() -> Path:
    d = Path(config.PLANS_DIR)
    d.mkdir(parents=True, exist_ok=True)
    return d


def save(day: date, title: str, markdown: str) -> Path:
    """Write a field guide to ``Plans/<YYYY-MM-DD>_<slug>.md`` (disambiguated if the
    name already exists) and return its path."""
    d = _plans_dir()
    stem = f"{day.isoformat()}_{_slugify(title)}"
    path = d / f"{stem}.md"
    i = 1
    while path.exists():
        path = d / f"{stem}_{i}.md"
        i += 1
    path.write_text(markdown, encoding="utf-8")
    return path


_TITLE_RE = re.compile(r"^#\s+(.*)")


def _title_of(path: Path) -> str:
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            m = _TITLE_RE.match(line)
            if m:
                return m.group(1).strip()
    except OSError:
        pass
    return path.stem


def list_guides() -> list[dict]:
    """Saved field guides, newest first: ``[{path, name, date, title}]``. ``date``
    is parsed from the filename prefix when present, else the file mtime date."""
    d = Path(config.PLANS_DIR)
    if not d.is_dir():
        return []
    out = []
    for p in d.glob("*.md"):
        m = re.match(r"(\d{4}-\d{2}-\d{2})_", p.name)
        dt = m.group(1) if m else date.fromtimestamp(p.stat().st_mtime).isoformat()
        out.append({"path": p, "name": p.name, "date": dt, "title": _title_of(p)})
    out.sort(key=lambda g: (g["date"], g["name"]), reverse=True)
    return out


def read(path) -> str:
    return Path(path).read_text(encoding="utf-8")
