#!/usr/bin/env python3
"""Generate additional bundled catalogs (dev/build-time tool — needs astroquery +
network). Companion to gen_caldwell.py.

For each catalog below it resolves coordinates / angular size / magnitude / type via
Simbad and emits:
  * one membership file  m110/seed/catalogs/<id>.toml   (slug → catalog designation)
  * reference entries for any *new* objects, appended to m110/seed/objects.toml in a
    dedicated, idempotently-regenerated section (objects already shipped by Messier /
    Caldwell are reused, never duplicated).

Catalogs:
  - rasc-finest    RASC Finest NGC (110; Alan Dyer's Observer's Handbook list)
  - sharpless-best curated "best of" Sharpless Sh2 emission nebulae (imaging picks)
  - bennett        Bennett Catalogue (152; southern comet-like objects)
  - lacaille       Lacaille 1755 (southern; deep-sky members only)

Runtime stays offline — only the bundled output ships. Re-runs only add data: Simbad
misses fall back to already-bundled values, and the objects.toml section is rebuilt
in place between markers (so gen_caldwell.py and this tool coexist — gen_caldwell
preserves this section as a tail).

    python tools/gen_catalogs.py
"""
from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

SEED = Path(__file__).resolve().parent.parent / "m110" / "seed"
sys.path.insert(0, str(SEED.parent.parent))
from m110.catalog import season_from_ra            # noqa: E402

# Section of objects.toml owned by this tool (regenerated in place each run; the
# Messier/Caldwell sections above it are left untouched, and gen_caldwell preserves
# everything from this marker on as a tail).
EXTRA_MARKER = ("# ════════════ Additional bundled catalogs (generated by "
                "tools/gen_catalogs.py) ════════════")


# ── source lists ─────────────────────────────────────────────────────────────

# RASC Finest NGC — "designation|common name|RASC type code|constellation".
# Bare numbers are NGC; "I nnn" is IC; "a/b" composites take the first component.
_RASC = """\
7009|Saturn Nebula|PN|Aqr
7293|Helix Nebula|PN|Aqr
7331||G|Peg
7635|Bubble Nebula|EN|Cas
7789||OC|Cas
185||G|Cas
281||EN|Cas
457||OC|Cas
663||OC|Cas
I 289||PN|Cas
7662|Blue Snowball|PN|And
891||G|And
253||G|Scl
772||G|Ari
246||PN|Cet
936||G|Cet
869/84|Double Cluster|OC|Per
1023||G|Per
1491||EN|Per
1501||PN|Cam
1232||G|Eri
1535||PN|Eri
1514||PN|Tau
1931||EN|Aur
1788||RN|Ori
1973||RN|Ori
2022||PN|Ori
2024||EN|Ori
2194||OC|Ori
2371/2||PN|Gem
2392|Eskimo Nebula|PN|Gem
2237|Rosette Nebula|EN|Mon
2261|Hubble's Variable Nebula|RN|Mon
2359||EN|CMa
2440||PN|Pup
2539||OC|Pup
2403||G|Cam
2655||G|Cam
2683||G|Lyn
2841||G|UMa
3079||G|UMa
3184||G|UMa
3877||G|UMa
3941||G|UMa
4026||G|UMa
4088||G|UMa
4157||G|UMa
4605||G|UMa
3115|Spindle Galaxy|G|Sex
3242|Ghost of Jupiter|PN|Hya
3003||G|LMi
3344||G|LMi
3432||G|LMi
2903||G|Leo
3384||G|Leo
3521||G|Leo
3607||G|Leo
3628||G|Leo
4111||G|CVn
4214||G|CVn
4244||G|CVn
4449||G|CVn
4490||G|CVn
4631||G|CVn
4656/7||G|CVn
5005||G|CVn
5033||G|CVn
4274||G|Com
4414||G|Com
4494||G|Com
4559||G|Com
4565|Needle Galaxy|G|Com
4725||G|Com
4038/9|Antennae|G|Crv
4361||PN|Crv
4216||G|Vir
4388||G|Vir
4438||G|Vir
4517||G|Vir
4526|Lost Galaxy|G|Vir
4535||G|Vir
4567/8|Siamese Twins|G|Vir
4699||G|Vir
4762||G|Vir
5746||G|Vir
5466||GC|Boo
5907||G|Dra
6503||G|Dra
6543|Cat's Eye Nebula|PN|Dra
6210||PN|Her
6369|Little Ghost Nebula|PN|Oph
6572||PN|Oph
6633||OC|Oph
6712||GC|Sct
6781||PN|Aql
6819||OC|Cyg
6826|Blinking Planetary|PN|Cyg
6888|Crescent Nebula|SNR|Cyg
6960|Veil Nebula (west)|SNR|Cyg
6992/5|Veil Nebula (east)|SNR|Cyg
7000|North America Nebula|EN|Cyg
7027||PN|Cyg
6445||PN|Sgr
6520||OC|Sgr
6818|Little Gem Nebula|PN|Sgr
6802||OC|Vul
6940||OC|Vul
6939||OC|Cep
6946|Fireworks Galaxy|G|Cep
7129||RN|Cep
40|Bow-Tie Nebula|PN|Cep
"""

# Curated "Best of Sharpless" — bright Sh2 emission nebulae popular for smart-scope
# narrowband/LP imaging. "Sh2 designation|common name|type".
_SHARPLESS = """\
Sh2-101|Tulip Nebula|emission
Sh2-106|Celestial Snow Angel|emission
Sh2-112||emission
Sh2-115||emission
Sh2-119||emission
Sh2-124||emission
Sh2-129|Flying Bat Nebula|emission
Sh2-132|Lion Nebula|emission
Sh2-140||emission
Sh2-142|Wizard Nebula|emission
Sh2-155|Cave Nebula|emission
Sh2-157|Lobster Claw Nebula|emission
Sh2-170|Little Rosette Nebula|emission
Sh2-171|NGC 7822|emission
Sh2-188|Dolphin Head Nebula|planetary
Sh2-190|Heart Nebula|emission
Sh2-199|Soul Nebula|emission
Sh2-216||planetary
Sh2-220|California Nebula|emission
Sh2-224||emission_snr
Sh2-229|Flaming Star Nebula|emission
Sh2-240|Spaghetti Nebula|emission_snr
Sh2-248|Jellyfish Nebula|emission_snr
Sh2-261|Lower's Nebula|emission
Sh2-264|Lambda Orionis Ring|emission
Sh2-273|Cone and Fox Fur Nebula|emission
Sh2-276|Barnard's Loop|emission
Sh2-279|Running Man Nebula|reflection
Sh2-296|Seagull Nebula|emission
Sh2-308|Dolphin Nebula|emission
"""

# Bennett Catalogue — authoritative ASSA numbering ("Bennett number|designation").
# Source: A. Slotegraaf (ed.), "Jack Bennett's Catalogue of Southern Comet-like
# Deep-sky Objects", ASSA Deep-Sky Section, v4.2 (2013). Note the supplementary
# sub-numbers (Ben 10a, 14a, …) and that Ben 72a is Trumpler 23 (not Cr 259, a
# Stellarium-script mislabel) and Ben 12 is NGC 1291 (not 1269). Names/types from Simbad.
_BENNETT = """\
Ben 1|NGC 55
Ben 2|NGC 104
Ben 3|NGC 247
Ben 4|NGC 253
Ben 5|NGC 288
Ben 6|NGC 300
Ben 7|NGC 362
Ben 8|NGC 613
Ben 9|NGC 1068
Ben 10|NGC 1097
Ben 10a|NGC 1232
Ben 11|NGC 1261
Ben 12|NGC 1291
Ben 13|NGC 1313
Ben 14|NGC 1316
Ben 14a|NGC 1350
Ben 15|NGC 1360
Ben 16|NGC 1365
Ben 17|NGC 1380
Ben 18|NGC 1387
Ben 19|NGC 1399
Ben 19a|NGC 1398
Ben 20|NGC 1404
Ben 21|NGC 1433
Ben 21a|NGC 1512
Ben 22|NGC 1535
Ben 23|NGC 1549
Ben 24|NGC 1553
Ben 25|NGC 1566
Ben 25a|NGC 1617
Ben 26|NGC 1672
Ben 27|NGC 1763
Ben 28|NGC 1783
Ben 29|NGC 1792
Ben 30|NGC 1818
Ben 31|NGC 1808
Ben 32|NGC 1851
Ben 33|NGC 1866
Ben 34|NGC 1904
Ben 35|NGC 2070
Ben 36|NGC 2214
Ben 36a|NGC 2243
Ben 37|NGC 2298
Ben 37a|NGC 2467
Ben 38|NGC 2489
Ben 39|NGC 2506
Ben 40|NGC 2627
Ben 40a|NGC 2671
Ben 41|NGC 2808
Ben 41a|NGC 2972
Ben 41b|NGC 2997
Ben 42|NGC 3115
Ben 43|NGC 3132
Ben 44|NGC 3201
Ben 45|NGC 3242
Ben 46|NGC 3621
Ben 47|Mel 105
Ben 48|NGC 3960
Ben 49|NGC 3923
Ben 50|NGC 4372
Ben 51|NGC 4590
Ben 52|NGC 4594
Ben 53|NGC 4697
Ben 54|NGC 4699
Ben 55|NGC 4753
Ben 56|NGC 4833
Ben 57|NGC 4945
Ben 58|NGC 4976
Ben 59|NGC 5061
Ben 59a|NGC 5068
Ben 60|NGC 5128
Ben 61|NGC 5139
Ben 62|NGC 5189
Ben 63|NGC 5236
Ben 63a|NGC 5253
Ben 64|NGC 5286
Ben 65|NGC 5617
Ben 66|NGC 5634
Ben 67|NGC 5824
Ben 68|NGC 5897
Ben 69|NGC 5927
Ben 70|NGC 5986
Ben 71|NGC 5999
Ben 72|NGC 6005
Ben 72a|Trumpler 23
Ben 73|NGC 6093
Ben 74|NGC 6101
Ben 75|NGC 6121
Ben 76|NGC 6134
Ben 77|NGC 6144
Ben 78|NGC 6139
Ben 79|NGC 6171
Ben 79a|NGC 6167
Ben 79b|NGC 6192
Ben 80|NGC 6218
Ben 81|NGC 6216
Ben 82|NGC 6235
Ben 83|NGC 6254
Ben 84|NGC 6253
Ben 85|NGC 6266
Ben 86|NGC 6273
Ben 87|NGC 6284
Ben 88|NGC 6287
Ben 89|NGC 6293
Ben 90|NGC 6304
Ben 91|NGC 6316
Ben 91a|NGC 6318
Ben 92|NGC 6333
Ben 93|NGC 6356
Ben 94|NGC 6352
Ben 95|NGC 6362
Ben 96|NGC 6388
Ben 97|NGC 6402
Ben 98|NGC 6397
Ben 98a|NGC 6440
Ben 98b|NGC 6445
Ben 99|NGC 6441
Ben 100|NGC 6496
Ben 101|NGC 6522
Ben 102|NGC 6528
Ben 103|NGC 6544
Ben 104|NGC 6541
Ben 105|NGC 6553
Ben 106|NGC 6569
Ben 107|NGC 6584
Ben 107a|NGC 6603
Ben 108|NGC 6618
Ben 109|NGC 6624
Ben 110|NGC 6626
Ben 111|NGC 6638
Ben 112|NGC 6637
Ben 112a|NGC 6642
Ben 113|NGC 6652
Ben 114|NGC 6656
Ben 115|NGC 6681
Ben 116|NGC 6705
Ben 117|NGC 6712
Ben 118|NGC 6715
Ben 119|NGC 6723
Ben 120|NGC 6744
Ben 121|NGC 6752
Ben 122|NGC 6809
Ben 123|NGC 6818
Ben 124|NGC 6864
Ben 125|NGC 6981
Ben 126|NGC 7009
Ben 127|NGC 7089
Ben 128|NGC 7099
Ben 129|NGC 7293
Ben 129a|NGC 7410
Ben 129b|IC 1459
Ben 130|NGC 7793
"""

# Lacaille 1755 (southern) — "Lacaille designation|modern designation|type"
# (deep-sky members only; plain asterisms/stars omitted).
_LACAILLE = """\
Lac I.1|NGC 104|globular
Lac I.2|NGC 2070|emission
Lac I.3|NGC 2477|open_cluster
Lac I.4|NGC 4833|globular
Lac I.5|NGC 5139|globular
Lac I.6|M83|galaxy
Lac I.8|NGC 6124|open_cluster
Lac I.9|M4|globular
Lac I.10|NGC 6242|open_cluster
Lac I.12|M22|globular
Lac I.14|M55|globular
Lac II.3|NGC 2516|open_cluster
Lac II.4|NGC 2546|open_cluster
Lac II.5|IC 2391|open_cluster
Lac II.7|NGC 3228|open_cluster
Lac II.8|NGC 3293|open_cluster
Lac II.9|IC 2602|open_cluster
Lac II.10|NGC 3532|open_cluster
Lac II.12|NGC 4755|open_cluster
Lac II.14|M7|open_cluster
Lac III.2|NGC 2547|open_cluster
Lac III.4|IC 2488|open_cluster
Lac III.6|NGC 3372|emission
Lac III.7|NGC 3766|open_cluster
Lac III.8|NGC 5662|open_cluster
Lac III.10|NGC 6025|open_cluster
Lac III.11|NGC 6397|globular
Lac III.12|M6|open_cluster
Lac III.13|M8|emission
"""


# ── type mapping ──────────────────────────────────────────────────────────────

_RASC_TYPE = {"PN": "planetary", "OC": "open_cluster", "GC": "globular",
              "EN": "emission", "RN": "reflection", "SNR": "emission_snr",
              "G": "galaxy"}

_SIMBAD_TYPE = {
    "PN": "planetary", "pl": "planetary",
    "GlC": "globular", "GlCl": "globular",
    "OpC": "open_cluster", "OpCl": "open_cluster", "Cl*": "open_cluster",
    "HII": "emission", "EmN": "emission", "ISM": "emission", "MoC": "emission",
    "RNe": "reflection",
    "SNR": "emission_snr", "SR?": "emission_snr",
    "DNe": "dark_nebula",
    "G": "galaxy", "GiG": "galaxy", "GiP": "galaxy", "IG": "galaxy",
    "PaG": "galaxy", "GrG": "galaxy", "SBG": "galaxy", "AGN": "galaxy",
    "Sy1": "galaxy", "Sy2": "galaxy", "rG": "galaxy", "H2G": "galaxy",
    "LIN": "galaxy", "EmG": "galaxy", "Sy*": "galaxy", "Sy?": "galaxy",
    "BiC": "galaxy", "SyG": "galaxy", "AG?": "galaxy", "G?": "galaxy",
    "As*": "open_cluster",                    # stellar association ≈ cluster
}


def _map_simbad_type(otype: str) -> str:
    return _SIMBAD_TYPE.get((otype or "").strip(), "unknown")


# ── designation normalisation ─────────────────────────────────────────────────

def _norm_rasc(desig: str) -> str:
    """RASC bare number / 'I nnn' / composite → a Simbad-resolvable designation."""
    d = desig.strip()
    if "/" in d:                                   # composite → first component
        d = d.split("/")[0]
    if d.startswith("I "):
        return "IC " + d[2:].strip()
    if re.fullmatch(r"\d+", d):
        return "NGC " + d
    return d


def _slug(name: str) -> str:
    return name.lower().replace(" ", "-").replace("/", "-")


def _toml_str(s) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _member_key(slug: str) -> str:
    return slug if re.fullmatch(r"[A-Za-z0-9_-]+", slug) else _toml_str(slug)


# ── Simbad ────────────────────────────────────────────────────────────────────

def _query_simbad(names):
    """{input-id: row} for the given designations. Empty on offline/missing."""
    try:
        from astroquery.simbad import Simbad
        sim = Simbad()
        sim.add_votable_fields("V", "dim", "otype")
        res = sim.query_objects(names)
        out = {}
        for row in res:
            key = (str(row["user_specified_id"]).strip()
                   if "user_specified_id" in res.colnames else None)
            out[key] = row
        return out
    except Exception as e:
        print(f"  Simbad unavailable ({type(e).__name__}); using bundled values.")
        return {}


def _extract(row):
    """(ra, dec, size, mag, otype) from a Simbad row, with NaN/mask guards."""
    ra = dec = size = mag = None
    otype = ""
    if row is None:
        return ra, dec, size, mag, otype
    try:
        if row["ra"] is not None and not getattr(row["ra"], "mask", False):
            ra = round(float(row["ra"]), 5)
            dec = round(float(row["dec"]), 5)
    except Exception:
        pass
    try:
        maj = float(row["galdim_majaxis"]); minr = float(row["galdim_minaxis"])
        if maj == maj:
            size = f"{maj:.0f}'×{minr:.0f}'" if minr == minr else f"{maj:.0f}'"
    except Exception:
        pass
    try:
        v = float(row["V"])
        if v == v:
            mag = round(v, 1)
    except Exception:
        pass
    try:
        otype = str(row["otype"]).strip()
    except Exception:
        pass
    return ra, dec, size, mag, otype


# ── catalog specs ──────────────────────────────────────────────────────────────

def _rasc_spec():
    objs = []
    for line in _RASC.strip().splitlines():
        desig, name, code, _const = line.split("|")
        canon = _norm_rasc(desig)
        objs.append({"query": canon, "member": canon, "name": name,
                     "type": _RASC_TYPE.get(code, "unknown")})
    return {"id": "rasc-finest", "name": "RASC Finest NGC",
            "description": "The RASC Observer's Handbook 'Finest NGC' list — 110 "
                           "deep-sky objects curated as the finest beyond Messier.",
            "objects": objs}


def _sharpless_spec():
    objs = []
    for line in _SHARPLESS.strip().splitlines():
        desig, name, otype = line.split("|")
        objs.append({"query": desig, "member": desig, "name": name, "type": otype})
    return {"id": "sharpless-best", "name": "Best of Sharpless",
            "description": "A curated selection of the brightest, most photogenic "
                           "Sharpless (Sh2) emission nebulae for smart-scope imaging.",
            "objects": objs}


def _bennett_spec():
    objs = []
    for line in _BENNETT.strip().splitlines():
        ben, desig = line.split("|")
        objs.append({"query": desig, "member": ben, "name": "",
                     "type": None})            # type from Simbad
    return {"id": "bennett", "name": "Bennett Catalogue",
            "description": "Jack Bennett's 152 southern comet-like deep-sky objects "
                           "— a southern-hemisphere complement to Messier.",
            "objects": objs}


def _lacaille_spec():
    objs = []
    for line in _LACAILLE.strip().splitlines():
        lac, modern, otype = line.split("|")
        objs.append({"query": modern, "member": lac, "name": "", "type": otype})
    return {"id": "lacaille", "name": "Lacaille 1755",
            "description": "Lacaille's 1755 catalogue of southern nebulae — the first "
                           "systematic southern deep-sky list (deep-sky members).",
            "objects": objs}


CATALOGS = [_rasc_spec(), _sharpless_spec(), _bennett_spec(), _lacaille_spec()]


# ── main ────────────────────────────────────────────────────────────────────--

def main():
    obj_path = SEED / "objects.toml"
    content = obj_path.read_text()
    head = content.split("\n" + EXTRA_MARKER, 1)[0].rstrip("\n")
    head_objs = tomllib.loads(head).get("object", {})       # Messier + Caldwell
    bundled_all = tomllib.loads(content).get("object", {})  # incl. prior extras

    # Resolve every distinct designation once.
    all_queries = []
    for cat in CATALOGS:
        for o in cat["objects"]:
            all_queries.append(o["query"])
    by_name = _query_simbad(sorted(set(all_queries)))

    new_blocks, emitted, unresolved = [], set(), []
    for cat in CATALOGS:
        members = []
        for o in cat["objects"]:
            slug = _slug(o["query"])
            members.append((slug, o["member"]))
            if slug in head_objs:
                continue                       # reuse Messier/Caldwell reference entry
            if slug in emitted:
                continue                       # shared across catalogs → emit once
            row = by_name.get(o["query"])
            ra, dec, size, mag, otype = _extract(row)
            prev = bundled_all.get(slug, {})   # re-run fallback
            if ra is None and prev.get("ra_deg") is not None:
                ra, dec = prev["ra_deg"], prev.get("dec_deg")
            if size is None:
                size = prev.get("size")
            if mag is None:
                mag = prev.get("magnitude")
            otype_mapped = o["type"] or _map_simbad_type(otype) or "unknown"
            if otype_mapped == "unknown" and prev.get("type"):
                otype_mapped = prev["type"]
            season = season_from_ra(ra) if ra is not None else prev.get("season")
            if ra is None:
                unresolved.append(o["query"])
            emitted.add(slug)
            block = [f"\n[object.{slug}]", f"id = {_toml_str(o['query'])}"]
            if o["name"]:
                block.append(f"name = {_toml_str(o['name'])}")
            block.append(f"type = {_toml_str(otype_mapped)}")
            if mag is not None:
                block.append(f"magnitude = {mag}")
            if size:
                block.append(f"size = {_toml_str(size)}")
            if season:
                block.append(f"season = {_toml_str(season)}")
            if ra is not None:
                block.append(f"ra_deg = {ra}")
                block.append(f"dec_deg = {dec}")
            new_blocks.append("\n".join(block))

        # membership file
        lines = [f"name = {_toml_str(cat['name'])}",
                 f"description = {_toml_str(cat['description'])}", "", "[members]"]
        for slug, desig in members:
            lines.append(f"{_member_key(slug)} = {_toml_str(desig)}")
        (SEED / "catalogs" / f"{cat['id']}.toml").write_text("\n".join(lines) + "\n")
        print(f"  {cat['id']}: {len(members)} members")

    # rewrite the objects.toml extra section in place
    body = head + "\n\n" + EXTRA_MARKER + "\n" \
        + "# Reference entries for catalog objects not already shipped by Messier/" \
          "Caldwell.\n" + "\n".join(new_blocks) + "\n"
    obj_path.write_text(body)
    print(f"objects.toml: +{len(new_blocks)} new reference entries.")
    if unresolved:
        print(f"  UNRESOLVED coords ({len(unresolved)}): {unresolved}")


if __name__ == "__main__":
    main()
